// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBebd8fXw0Gjq0k10HFVX7AY4u9hOGSzeI',
    appId: '1:812571147067:web:81f50a56690c33465f951e',
    messagingSenderId: '812571147067',
    projectId: 'chat-community-4c478',
    authDomain: 'chat-community-4c478.firebaseapp.com',
    storageBucket: 'chat-community-4c478.appspot.com',
    measurementId: 'G-PFHZ8PBGL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7WX5ic7642pCNaPX8f84KbiZqWjCKOUU',
    appId: '1:812571147067:android:93170bae344dd4bf5f951e',
    messagingSenderId: '812571147067',
    projectId: 'chat-community-4c478',
    storageBucket: 'chat-community-4c478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb2ABwHaU7RPnZ7r57ho7fig1yHExDUaU',
    appId: '1:812571147067:ios:78fe802d8540d9ed5f951e',
    messagingSenderId: '812571147067',
    projectId: 'chat-community-4c478',
    storageBucket: 'chat-community-4c478.appspot.com',
    iosBundleId: 'com.example.chatCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb2ABwHaU7RPnZ7r57ho7fig1yHExDUaU',
    appId: '1:812571147067:ios:e40892d8afe2c38b5f951e',
    messagingSenderId: '812571147067',
    projectId: 'chat-community-4c478',
    storageBucket: 'chat-community-4c478.appspot.com',
    iosBundleId: 'com.example.chatCommunity.RunnerTests',
  );
}
